[package]
name = "RustAstrology"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
getrandom = { version = "0.2", features = ["js"] }
async-trait = "0.1.88"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
js-sys = "0.3.77"
leptos = "0.7.0"
leptos_router = "0.7.0"
log = "0.4.27"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"
serde_with = "3.12.0"
tauri = { version = "2", optional = true }
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["sync", "macros", "io-util", "rt", "time"], optional = true }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
wasm-logger = "0.2.0"
web-sys = "0.3.77"

[features]
default = ["wasm"]
wasm = ["getrandom/js"]
desktop = ["tokio/full", "tauri"]

[build-dependencies]
tauri-build = "2.2.0"