[package]
name = "rust-astrology"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A Rust Astrology application with Qt interface"
license = "MIT OR Apache-2.0"
repository = ""

[dependencies]
anyhow = "1.0.98"
log = "0.4.27"
env_logger = "0.11"
thiserror = "2.0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Qt bindings using qmetaobject
qmetaobject = "0.2.10"

# For async support (optional)
tokio = { version = "1.0", features = ["full"], optional = true }

[features]
default = ["desktop"]
desktop = []

[build-dependencies]
cc = "1.0"