[build]
target = "index.html"
public_url = "/"
dist = "dist"

[serve]
addresses = ["127.0.0.1"]
port = 3001
open = false

# Simplified wasm settings to avoid pipeline issues
[build.wasm]
opt-level = 2