[build]
target = "index.html"
public_url = "/"
dist = "dist"
build = ".dist"
watch = true
port = 8080
host = "127.0.0.1"
http2 = false
compress = false
directory_listing = false
release = false
profile = "debug"

# Hooks are now managed separately in the dev.sh script
# to better handle the separation between WASM and Tauri

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = false